# Generated by Django 5.2.15 on 2026-06-05 05:20

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('report_year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('industry_category', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('ocr_processing', 'OCR Processing'), ('embedding', 'Embedding'), ('retrieving', 'Retrieving'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('generating_pdf', 'Generating PDF'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=40)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='zh-Hant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('ocr_processing', 'OCR Processing'), ('embedding', 'Embedding'), ('retrieving', 'Retrieving'), ('analyzing', 'Analyzing'), ('scoring', 'Scoring'), ('generating_pdf', 'Generating PDF'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=40)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('chunk_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('table', 'Table'), ('section', 'Section'), ('ocr', 'OCR')], default='paragraph', max_length=40)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'page_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploaded_reports/', validators=[reports.models.validate_pdf])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_record', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('raw_text', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('final_text', models.TextField(blank=True)),
                ('extraction_method', models.CharField(default='pymupdf', max_length=40)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('needs_ocr', models.BooleanField(default=False)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'page_number'],
                'unique_together': {('report', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('engine', models.CharField(default='pytesseract', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='reports.report')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='reports.reportpage')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=list)),
                ('extracted_text', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reports.report')),
            ],
        ),
    ]
