# Generated by Django 5.2.15 on 2026-06-06 09:51

import django.db.models.deletion
from django.db import migrations, models


def set_latest_analysis_links(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    AnalysisJob = apps.get_model("reports", "AnalysisJob")
    AnalysisResult = apps.get_model("analysis", "AnalysisResult")
    for report in Report.objects.all().iterator():
        latest_job = AnalysisJob.objects.filter(report=report).order_by("-created_at", "-id").first()
        latest_result = AnalysisResult.objects.filter(report=report).order_by("-version_number", "-analyzed_at", "-id").first()
        update_fields = []
        if latest_job:
            report.latest_analysis_job_id = latest_job.id
            update_fields.append("latest_analysis_job")
        if latest_result:
            latest_result.is_latest = True
            latest_result.version_number = latest_result.version_number or 1
            if latest_job and not latest_result.analysis_job_id:
                latest_result.analysis_job_id = latest_job.id
            latest_result.save(update_fields=["is_latest", "version_number", "analysis_job"])
            report.latest_analysis_result_id = latest_result.id
            update_fields.append("latest_analysis_result")
        if update_fields:
            report.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisresult_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='purpose',
            field=models.CharField(choices=[('upload', 'Initial Upload'), ('reanalysis', 'Reanalysis')], default='upload', max_length=40),
        ),
        migrations.AddField(
            model_name='report',
            name='latest_analysis_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.analysisjob'),
        ),
        migrations.AddField(
            model_name='report',
            name='latest_analysis_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analysis.analysisresult'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='reports.report'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['report', '-created_at'], name='reports_ana_report__f300a8_idx'),
        ),
        migrations.RunPython(set_latest_analysis_links, migrations.RunPython.noop),
    ]
