# Generated by Django 5.2.15 on 2026-06-05 05:20

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CitationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(blank=True, max_length=40)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quoted_text', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('dimensions', models.PositiveIntegerField(default=3072)),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(blank=True, max_length=40)),
                ('query', models.TextField()),
                ('matched_chunk_ids', models.JSONField(blank=True, default=list)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('gri', 'GRI'), ('benchmark', 'Benchmark'), ('report', 'User Report'), ('regulation', 'Regulation')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
