# Generated by Django 5.2.15 on 2026-06-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationsource',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='retrievallog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='citationsource',
            name='retrieval_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='rag.retrievallog'),
        ),
        migrations.AddField(
            model_name='vectorchunk',
            name='report_chunk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportchunk'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='vector_chunk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='rag.vectorchunk'),
        ),
        migrations.AddField(
            model_name='citationsource',
            name='vector_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag.vectorchunk'),
        ),
        migrations.AddField(
            model_name='vectordocument',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vector_documents', to='reports.report'),
        ),
        migrations.AddField(
            model_name='vectorchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.vectordocument'),
        ),
    ]
