# Generated by Django 5.2.15 on 2026-06-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='embedding',
            table='embeddings',
        ),
        migrations.AlterModelTable(
            name='vectorchunk',
            table='document_chunks',
        ),
        migrations.AlterModelTable(
            name='vectordocument',
            table='vector_documents',
        ),
    ]
