# Generated by Django 5.2.15 on 2026-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('operation', models.CharField(max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(default='v1', max_length=40)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisclosureScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('missing', 'Missing')], default='missing', max_length=20)),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('agent_output', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['disclosure_code'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('page_number', models.PositiveIntegerField()),
                ('quoted_text', models.TextField()),
                ('normalized_finding', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_char', models.PositiveIntegerField(blank=True, null=True)),
                ('end_char', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_type', models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('ocr', 'OCR'), ('inferred', 'Inferred')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['disclosure_code', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generated_reports/')),
                ('html_snapshot', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('recommendation', models.TextField()),
                ('term', models.CharField(choices=[('short', 'Short Term'), ('medium', 'Medium Term'), ('long', 'Long Term')], default='short', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'term'],
            },
        ),
        migrations.CreateModel(
            name='MissingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(default='medium', max_length=40)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['priority', 'disclosure_code'],
            },
        ),
    ]
