# Generated by Django 5.2.15 on 2026-06-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='reports.report'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='analysis_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='disclosurescore',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_scores', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='evidencecitation',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_citations', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='evidencecitation',
            name='disclosure_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_citations', to='analysis.disclosurescore'),
        ),
        migrations.AddField(
            model_name='evidencecitation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_citations', to='reports.report'),
        ),
        migrations.AddField(
            model_name='evidencecitation',
            name='source_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportchunk'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='improvementrecommendation',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='missingitem',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_items', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='missingitem',
            name='disclosure_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_items', to='analysis.disclosurescore'),
        ),
        migrations.AlterUniqueTogether(
            name='disclosurescore',
            unique_together={('analysis_result', 'disclosure_code')},
        ),
    ]
