# Generated by Django 5.2.15 on 2026-06-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-version_number', '-analyzed_at']},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_result', to='reports.analysisjob'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='reports.report'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('report', 'version_number')},
        ),
    ]
