# Generated by Django 5.2.15 on 2026-06-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisresult_options_and_more'),
        ('reports', '0003_industrycategory_report_company_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('min_percentile_rank', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-min_percentile_rank', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='IndustryMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentile_rank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('z_score', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('grade', models.CharField(db_index=True, default='D', max_length=5)),
                ('disclosure_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('recommendation_count', models.PositiveIntegerField(default=0)),
                ('benchmark_sample_size', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_metric', to='analysis.analysisresult')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='reports.industrycategory')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_metric', to='reports.report')),
            ],
            options={
                'ordering': ['industry__code', '-percentile_rank', '-raw_score'],
                'indexes': [models.Index(fields=['industry', '-percentile_rank'], name='analysis_in_industr_4911cc_idx'), models.Index(fields=['grade'], name='analysis_in_grade_383947_idx'), models.Index(fields=['calculated_at'], name='analysis_in_calcula_39ed0a_idx')],
            },
        ),
    ]
