# Generated by Django 5.2.15 on 2026-06-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRIDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('disclosure_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_keywords', models.JSONField(blank=True, default=list)),
                ('required_data_points', models.JSONField(blank=True, default=list)),
                ('scoring_logic', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('version', models.CharField(default='2021', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['disclosure_code'],
            },
        ),
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='markdown', max_length=40)),
                ('file', models.FileField(blank=True, upload_to='regulations/')),
                ('body', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRICheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('data_points', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='gri.gridisclosure')),
            ],
            options={
                'ordering': ['disclosure__disclosure_code', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GRIStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='2021', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='gridisclosure',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='gri.gristandard'),
        ),
        migrations.CreateModel(
            name='RegulationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gri.regulationdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('logic', models.TextField()),
                ('score_when_missing', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('score_when_partial', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('score_when_complete', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='gri.gridisclosure')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gri.ruleversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disclosure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_weight', to='gri.gridisclosure')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gridisclosure',
            unique_together={('disclosure_code', 'version')},
        ),
    ]
