# Generated by Django 5.2.15 on 2026-06-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRIDisclosureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('rule_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('official_requirement', models.TextField(blank=True)),
                ('source_document', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='GRI 305:2016', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gri_disclosure_rules',
                'ordering': ['disclosure_code'],
                'unique_together': {('disclosure_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GRIRequiredField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('field_key', models.CharField(max_length=120)),
                ('field_label', models.CharField(max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('patterns', models.JSONField(blank=True, default=list)),
                ('recommendation_template', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=40)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gri_required_fields',
                'ordering': ['disclosure_code', 'sort_order'],
                'unique_together': {('disclosure_code', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='GRIScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_code', models.CharField(db_index=True, max_length=40)),
                ('field_key', models.CharField(max_length=120)),
                ('field_label', models.CharField(max_length=255)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gri_scoring_weights',
                'ordering': ['disclosure_code', 'sort_order'],
                'unique_together': {('disclosure_code', 'field_key')},
            },
        ),
    ]
