# Generated by Django 5.2.15 on 2026-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gri', '0002_gridisclosurerule_grirequiredfield_griscoringweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='grirequiredfield',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grirequiredfield',
            name='requirement_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='grirequiredfield',
            name='source_clause',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
